services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - dsa-network
  frontend-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - dsa-network

networks:
  dsa-network:
    external: true

volumes:
  db_data:




# services:
#   frontend:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#     restart: unless-stopped
#     networks:
#       - dsa-network
#   frontend-dev:
#     image: node:18-alpine
#     working_dir: /app
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: sh -c "npm install && npm run dev -- --host"
#     ports:
#       - "5173:5173"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     networks:
#       - dsa-network

# networks:
#   dsa-network:
#     driver: bridge

# volumes:
#   db_data: